// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCaJKnID647_YnFuPzBlnIeNeWfIgWf4',
    appId: '1:869939356915:web:048409c8c25ae06d94c386',
    messagingSenderId: '869939356915',
    projectId: 'smartfund-management',
    authDomain: 'smartfund-management.firebaseapp.com',
    storageBucket: 'smartfund-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtClmGWge43zuB5CQFvvqzaQ0YBcBgiGk',
    appId: '1:869939356915:android:56846ae88729e7af94c386',
    messagingSenderId: '869939356915',
    projectId: 'smartfund-management',
    storageBucket: 'smartfund-management.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxb2IVfRq8n3Dl5UavyAFasnOXcrWnKI',
    appId: '1:869939356915:ios:dd19a67defdc9d4d94c386',
    messagingSenderId: '869939356915',
    projectId: 'smartfund-management',
    storageBucket: 'smartfund-management.firebasestorage.app',
    iosBundleId: 'com.example.smartfundmanagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxb2IVfRq8n3Dl5UavyAFasnOXcrWnKI',
    appId: '1:869939356915:ios:dd19a67defdc9d4d94c386',
    messagingSenderId: '869939356915',
    projectId: 'smartfund-management',
    storageBucket: 'smartfund-management.firebasestorage.app',
    iosBundleId: 'com.example.smartfundmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCaJKnID647_YnFuPzBlnIeNeWfIgWf4',
    appId: '1:869939356915:web:c863b3e5f1e3b1a694c386',
    messagingSenderId: '869939356915',
    projectId: 'smartfund-management',
    authDomain: 'smartfund-management.firebaseapp.com',
    storageBucket: 'smartfund-management.firebasestorage.app',
  );
}
