# Appium Configuration
appium.server.url=http://127.0.0.1:4723/
platform.name=Android
automation.name=UiAutomator2
device.name=Android Emulator
app.package=com.example.smartfundmanagement
app.activity=com.example.smartfundmanagement.MainActivity
app.path=../build/app/outputs/flutter-apk/app-debug.apk

# Web Configuration
base.url=https://sureshdeepika876.github.io/smartfundmanagement_app/
browser=chrome
headless=true

# Framework Settings
implicit.wait=10
explicit.wait=15
screenshot.dir=target/TestResults/Screenshots/
logs.dir=target/TestResults/Logs/
excel.report.dir=target/TestResults/Excel/
html.report.dir=target/TestResults/HTML/
json.report.dir=target/TestResults/JSON/
summary.report.dir=target/TestResults/Summary/
retry.count=1
